services:
  - type: web
    name: ates-ve-su-online
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
